---
#development:
#  cloud_name: mirazhg
#  api_key: '946566432945743'
#  api_secret: zhSMCX4WGka4lNjwPFJlonlEUKM
#  enhance_image_tag: true
#  static_image_support: false
production:
  cloud_name: mirazhg
  api_key: '946566432945743'
  api_secret: zhSMCX4WGka4lNjwPFJlonlEUKM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mirazhg
  api_key: '946566432945743'
  api_secret: zhSMCX4WGka4lNjwPFJlonlEUKM
  enhance_image_tag: true
  static_image_support: false
